# Generated by Django 4.2.1 on 2023-07-08 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('post', models.CharField(max_length=100, verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='изображение')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('total_views', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_status', models.CharField(choices=[('AC', 'Active'), ('FI', 'Finished'), ('CR', 'Created')], default='CR', max_length=2, verbose_name='статус рассылки')),
                ('mailing_time_start', models.DateTimeField(blank=True, null=True, verbose_name='время начала рассылки')),
                ('mailing_time_end', models.DateTimeField(blank=True, null=True, verbose_name='время конца рассылки')),
                ('mailing_periods', models.CharField(choices=[('DL', 'Daily'), ('WL', 'Weekly'), ('ML', 'Monthly')], max_length=2, verbose_name='периодичность')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылки',
                'ordering': ['mailing_status'],
            },
        ),
        migrations.CreateModel(
            name='MailingTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_try', models.DateTimeField(auto_now=True, verbose_name='дата и время последней попытки')),
                ('mailing_try_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='статус рассылки')),
                ('mailing_response', models.CharField(blank=True, max_length=255, null=True, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_subject', models.CharField(max_length=255, verbose_name='тема письма')),
                ('mailing_body', models.CharField(max_length=500, verbose_name='тело письма')),
                ('all_clients', models.BooleanField(blank=True, null=True, verbose_name='все клиенты')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
                ('client_to_message', models.ManyToManyField(blank=True, null=True, related_name='client_to_message', to='client.mailingclient', verbose_name='Клиенты')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
